# Generated by Django 6.0.2 on 2026-03-12 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('neutral', 'Neutral')], default='primary', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_dynamic', models.BooleanField(default=True, help_text='Dynamic segments auto-update when rules change. Static segments are manually managed.', verbose_name='Dynamic')),
                ('customer_count', models.IntegerField(default=0, verbose_name='Customer Count')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Calculated')),
                ('logic_operator', models.CharField(choices=[('and', 'All rules must match (AND)'), ('or', 'Any rule must match (OR)')], default='and', max_length=3, verbose_name='Logic Operator')),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'db_table': 'segments_segment',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('auto_refresh_minutes', models.PositiveIntegerField(default=0, help_text='Set to 0 to disable automatic refresh. Segments will only refresh on demand.', verbose_name='Auto-refresh Interval (minutes)')),
                ('max_segment_size', models.PositiveIntegerField(default=10000, help_text='Maximum number of customers per segment. 0 for unlimited.', verbose_name='Max Segment Size')),
            ],
            options={
                'verbose_name': 'Segment Settings',
                'verbose_name_plural': 'Segment Settings',
                'db_table': 'segments_settings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('field', models.CharField(choices=[('lifecycle_stage', 'Lifecycle Stage'), ('source', 'Source'), ('total_spent', 'Total Spent'), ('total_purchases', 'Total Purchases'), ('last_purchase_date', 'Last Purchase Date'), ('city', 'City'), ('country', 'Country'), ('is_active', 'Is Active'), ('created_at', 'Created Date'), ('groups', 'Customer Group'), ('birthday_month', 'Birthday Month')], max_length=50, verbose_name='Field')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does Not Equal'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('greater_equal', 'Greater or Equal'), ('less_equal', 'Less or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('in_last_days', 'In Last X Days'), ('not_in_last_days', 'Not In Last X Days')], max_length=30, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Value')),
                ('value_type', models.CharField(choices=[('string', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='string', max_length=20, verbose_name='Value Type')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='segments.segment', verbose_name='Segment')),
            ],
            options={
                'verbose_name': 'Segment Rule',
                'verbose_name_plural': 'Segment Rules',
                'db_table': 'segments_segmentrule',
                'ordering': ['sort_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
